name: chat_app_example
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  
  firebase_core: ^0.4.0+6
  firebase_auth: ^0.15.2
  cloud_firestore: ^0.12.5+2
  firebase_storage:

  flutter_facebook_login: ^3.0.0
  image_picker: ^0.6.1+4
  geolocator: ^5.3.1
  provider: ^3.1.0
  google_sign_in: ^4.0.7
  firebase_ml_vision: ^0.9.2+1
  firebase_messaging: 6.0.13
  flutter_local_notifications: 1.4.0
  cached_network_image: 2.0.0-rc.1
  intl: ^0.15.7
  fluttertoast: ^3.1.3
  photo_view: ^0.5.0
  shared_preferences: ^0.5.3+4
  flutter_xlider: ^3.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
    
  assets:
    - assets/images/AmicaLogo.png
    - assets/images/flashscreen.png
    - assets/images/facebook-hd-png-facebook-png-hd-png-image-2023.png
    - assets/images/download.jpeg
    - assets/images/download.png
    - assets/images/logo.png
    - assets/images/a1.jpeg
    - assets/images/a2.jpeg
    - assets/images/a3.jpeg
    - assets/images/a4.jpeg
    - assets/images/a5.jpeg
    - assets/images/a6.jpeg
    - assets/images/a7.jpeg
    - assets/images/a8.jpeg
    - assets/images/a9.jpeg
    - assets/images/a11.jpeg
    - assets/images/a14.jpeg
    - assets/images/a15.jpeg
    - assets/images/a16.jpeg
    - assets/images/a18.jpeg
    - assets/images/a21.jpeg
    - assets/images/a22.jpeg
    - assets/images/fb.png
    - assets/images/gg.png
    - assets/images/ig.png
    - assets/images/mic.png
    - assets/images/tick.png
    - assets/images/cam.png
    - assets/images/cam1.png
    - assets/images/chart.png
    - assets/images/chat0.png
    - assets/images/music.png
    - assets/images/rewind.png
    - assets/images/sat.png
    - assets/images/trash.png
    - assets/images/list.png
    - assets/images/listsel.png
    - assets/images/grid.png
    - assets/images/gridsel.png
    - assets/images/chartsel.png
    - assets/images/trashsel.png
    - assets/images/satsel.png
    - assets/images/pen.png
    - assets/images/configure.png
    - assets/images/profile.png
    - assets/images/lang.png
    - assets/images/Amica1.jpeg
    - assets/images/Amica2.jpeg
    - assets/images/Amica3.jpeg
    - assets/images/Amica4.jpeg
    - assets/images/Amica5.jpg
    - assets/images/Amica6.jpeg
    - assets/images/Amica7.jpeg
    - assets/images/Amica8.jpeg
    - assets/images/Amica9.jpeg
    - assets/images/Amica10.jpeg
    - assets/images/Amica11.jpeg
    - assets/images/Amica13.jpeg
    - assets/images/Amica14.jpeg
    - assets/images/Amica16.jpeg
    - assets/images/Amica18.jpeg
    - assets/images/Amica19.jpeg


  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
     - family: Poppins
       fonts:
         - asset: fonts/Poppins-Bold.ttf
           style: italic

#     - family: Poppins1
#       fonts:
#         - asset: fonts/Poppins-Medium.ttf
#           style: italic
     - family: Poppins2
       fonts:
         - asset: fonts/Poppins-Regular.ttf
           style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
